require "keymaps"
require "options"
require "lazy_load"

require "configurations.bufferline"
require "configurations.cmp"
require "configurations.copilot"
require "configurations.gitsigns"
require "configurations.leap"
require "configurations.nvim_tree"
require "configurations.nvim_treesitter"
require "configurations.ui"
require "configurations.dap"

require "configurations.lsp.lspconfig"
require "configurations.lsp.keymaps"
